force-app/main/default/objects/Account/fields/Credit_Card__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card__c</fullName>
    <complianceGroup>PCI</complianceGroup>
    <description>asdas</description>
    <label>Credit Card</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WF_TestClass.cls
public with sharing class WF_TestClass {
    public WF_TestClass() {
        return [
        SELECT Id, Name, Active__c
        FROM Account
        WHERE Active__c = 'Yes'];
    }

    //Another comment. Changing one comment to test incremental build.
  //Changing one class to test inc build.//
  //adding a comment
  //adding another comment
  public static List<Account> getAllActiveAccounts() {
    return [
    SELECT Id, Name, Active__c
    FROM Account
    WHERE Active__c = 'Yes'];
  }
  //Gets all inactive accounts
  public static List<Account> getAllInactiveAccounts() {
      return [SELECT Id, Name, Active__c FROM Account WHERE Active__c = 'No'];
  }
  //Gets all the accounts, active and inactive.//
  public static List<Account> getAllAccounts() {
      return [SELECT Id, Name, Active__c, Credit_Card__c FROM Account];
  }
}