force-app/main/default/objects/Account/fields/SLASerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SLASerialNumber__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <label>SLA Serial Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HouseService.cls
public with sharing class HouseService {
    @AuraEnabled(cacheable=true)
    public static List<Account> getRecords() {
        try {
            
    		
            // Create a list of House records from a SOQL query
            List<Account> lstHouses = [
                SELECT Id, Name, Active__c, SLASerialNumber__c FROM Account
                ];
                  return lstHouses;
        }
        // Code to handle exception
        catch (Exception e) {
           throw new AuraHandledException(e.getMessage());
        }
    }
}